server:
  port: 8761
#  servlet:
#    context-path: /eurekaServer
eureka:
  instance:
    hostname: eurekaServer
  server:
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#eureka.instance.hostname=localhost
#eureka.client.fetch-registry=false
#eureka.client.register-with-eureka=false
#eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/