server:
  port: 5678
spring:
  application:
    name: voltepr

sidecar:
  port: 8081
#  health-uri: http://localhost:8080/eurekaClient/health.json
  health-uri: http://localhost:8081/voltepr/userController.do?health.json
eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: voltepr
    prefer-ip-address: true
    appname: voltepr